apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: key
  namespace: default
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: api-key-secret
  data:
  - secretKey: api-key
    remoteRef:
      key: "dev"
      property: "api-key"
